apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-server
  template:
    metadata:
      labels:
        app: fl-server
    spec:
      containers:
      - name: server
        image: your-registry/fl-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        - containerPort: 8000
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        volumeMounts:
        - name: model-volume
          mountPath: /data/models
        - name: dataset-volume
          mountPath: /data/dataset
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: dataset-pvc
